language: node_js
cache:
    yarn: true
    directories:
        - node_modules
node_js:
    - '8'
    - '10'
script:
    # - yarn test
    - mkdir .nyc_output && yarn report
sudo: false
after_success: yarn report
